### ISSUE TITLE
How to use my own models?

### ISSUE THREAD

**Issue by KarelWintersky** [getumbrel/llama-gpt#35]
How to use my own models?

**Comment by bolshoytoster** [comment]
@KarelWintersky if you're using docker, you can edit `docker-compose.yml`, changing `services.llama-gpt-api-7b.environment.MODEL`:
https://github.com/getumbrel/llama-gpt/blob/3553e20a3d4f8605040e4edab76f8094cb545da3/docker-compose.yml#L10-L12

to point to your model (looks like the path is local, so if your model is in the top level of the project it should be `/model-name.bin`), then you can run `docker compose up -d` and it should use your model.

**Comment by edgar971** [comment]
For example:

1. Find a GGML model from HuggingFace or your own
2. Copy the download link if using a HuggingFace model. 
3. Update the `docker-compose.yml` file.  

```yml

version: '3.6'

services:
  orca-mini-v3-70b:
    image: ghcr.io/abetlen/llama-cpp-python:latest
    restart: on-failure
    volumes:
      - './models:/models'
      - './api:/api'
    ports:
      - 3001:8000
    environment:
      MODEL: '/models/orca-mini-v3-70b.bin'
      MODEL_DOWNLOAD_URL: 'https://huggingface.co/TheBloke/orca_mini_v3_70B-GGML/resolve/main/orca_mini_v3_70b.ggmlv3.q4_0.bin'
    command: '/bin/sh /api/run.sh'

  llama-gpt-ui:
    image: 'ghcr.io/getumbrel/llama-gpt-ui:latest'
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - 'OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXX'
      - 'OPENAI_API_HOST=http://orca-mini-v3-70b:8000'
      - 'DEFAULT_MODEL=/models/orca-mini-v3-70b.bin'
      - 'WAIT_HOSTS=orca-mini-v3-70b:8000'
      - 'WAIT_TIMEOUT=3600'

```
