### ISSUE TITLE
CUDA / Metal support

### ISSUE THREAD

**Issue by khromov** [getumbrel/llama-gpt#6]
Since the API is built locally, it would be cool if there was a Metal-specific Dockerfile for macs (`LLAMA_METAL=1 make` should be enough for that)  and a CUDA build for Nvidia cards. (llama.cpp [provides CUDA images already](https://github.com/ggerganov/llama.cpp#docker-with-cuda) if that helps)

**Comment by mayankchhabra** [comment]
Totally agree! Would love to see CUDA and Metal support. Due to time constraints, we haven't been able to look deeply into adding them using [llama-cpp-python](https://github.com/abetlen/llama-cpp-python). That said, @khromov if this is something you can and would like to contribute, please feel free to go ahead!

**Comment by Belval** [comment]
I was able to get the 7B model running on a GTX 1080Ti. I built the llama-cpp-python image with CUDA support following this PR that hasn't been merged yet: https://github.com/abetlen/llama-cpp-python/pull/598

Then all I had to do was change run.sh to offload "1000" layers to GPU and add change the docker-compose.yml file to the following:

```
version: '3.6'

services:
  llama-gpt-api:
    # image: ghcr.io/getumbrel/llama-gpt-api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      MODEL: '/models/llama-2-7b-chat.bin'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  llama-gpt-ui:
    image: 'ghcr.io/getumbrel/llama-gpt-ui:latest'
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - 'OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXX'
      - 'OPENAI_API_HOST=http://llama-gpt-api:8000'
      - 'DEFAULT_MODEL=/models/llama-2-7b-chat.bin'
      - 'WAIT_HOSTS=llama-gpt-api:8000'
      - 'WAIT_TIMEOUT=600'
```

The important part being the deploy.

**Comment by peacepenguin** [comment]
Perhaps the deployment should use MLC concepts?

Llama models deployed using MLC has already proven effective, and enables Cuda, metal, rocm, etc, so the model can run on intel arc, amd Radeon as well.

https://mlc.ai/mlc-llm/docs/

Proof of concept notes:

https://blog.mlc.ai/2023/08/09/Making-AMD-GPUs-competitive-for-LLM-inference

**Comment by edicristofaro** [comment]
@Belval looks like that PR you linked to got merged a few minutes ago, fyi. i have a draft PR open to use the nvidia cuda images, but I'll close that since it seems like this will accomplish the same with fewer changes.

**Comment by Aincvy** [comment]
This is a temporary method for using CUDA. I tested it on Debian 11 and successfully ran the 13B model. *More information in the final part.*

**Short version**
- Compile llama-cpp-python's CUDA version docker image.
- Manually map the model to a container 
- Adjust and use the llama-gpt/api/run.sh file to start.


**Long version**
1. Install and set up Docker, including the [nvidia container-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)
2. git clone https://github.com/abetlen/llama-cpp-python.git
3. Prepare the model.
   1. llama-2-7b-chat.bin - https://huggingface.co/TheBloke/Nous-Hermes-Llama-2-7B-GGML/resolve/main/nous-hermes-llama-2-7b.ggmlv3.q4_0.bin
   2. llama-2-13b-chat.bin - https://huggingface.co/TheBloke/Nous-Hermes-Llama2-GGML/resolve/main/nous-hermes-llama2-13b.ggmlv3.q4_0.bin
   3. I think 7b or 13b is enough. 
   4. Download the model and place it in a host machine folder, such as `/home/debian/docker/llama-models`.
   5. I used the `llama-2-13b-chat.bin model`.
4. Review the documentation: https://github.com/abetlen/llama-cpp-python/tree/main/docker#cuda_simple.
   1. You do not need to execute the final `docker run` command, use `docker build -t cuda_simple . `to build the image.
5. Execute the command `sudo docker tag cuda_simple llama-cpp-python-cuda:latest`.
6. Find a directory as the Docker Compose directory, such as `/home/debian/docker-compose/llama-gpt-cuda`. 
7. Create a file `docker-compose.yaml` and fill in the following content.
```yaml
version: '3.6'

services:
  llama-gpt-api-13b:
    # image: 'ghcr.io/getumbrel/llama-gpt-api-llama-2-13b-chat:latest'
    image: 'llama-cpp-python-cuda:latest'
    # build:
    #   context: ./api
    #   dockerfile: 13B.Dockerfile
    restart: on-failure
    environment:
      MODEL: '/models/llama-2-13b-chat.bin'
      USE_MLOCK: 1
    volumes:
      - '/home/debian/docker/llama-models:/models/'
      - './data:/home'
    cap_add:
      - IPC_LOCK
      - SYS_RESOURCE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/sh /home/run.sh

  llama-gpt-ui:
    image: 'getumbrel/llama-gpt-ui:latest'
    container_name: 'llama-gpt-ui'
    ports: 
      - 3000:3000
    restart: on-failure
    environment:
      - 'OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXX'
      - 'OPENAI_API_HOST=http://llama-gpt-api-13b:8000'
      - 'DEFAULT_MODEL=/models/llama-2-13b-chat.bin'
      - 'WAIT_HOSTS=llama-gpt-api-13b:8000'
      - 'WAIT_TIMEOUT=600'

```
8. Create a directory: `data`. 
9. Create a file: `data/run.sh` and fill in the following content (copy from llama-gpt/api/run.sh and then adjust).
```shell
#!/bin/bash

# make build

# Get the number of available threads on the system
n_threads=$(grep -c ^processor /proc/cpuinfo)

# Define context window
n_ctx=4096

# Offload everything to CPU
n_gpu_layers=37      

# Define batch size
n_batch=2096
# If total RAM is less than 8GB, set batch size to 1024
total_ram=$(cat /proc/meminfo | grep MemTotal | awk '{print $2}')
if [ $total_ram -lt 8000000 ]; then
    n_batch=1024
fi

echo "Initializing server with:"
echo "Batch size: $n_batch"
echo "Number of CPU threads: $n_threads"
echo "Number of GPU layers: $n_gpu_layers"
echo "Context window: $n_ctx"

exec python3 -m llama_cpp.server --n_ctx $n_ctx --n_threads $n_threads --n_gpu_layers $n_gpu_layers --n_batch $n_batch
```  
10. Adjust the `n_gpu_layers` parameter, too large may cause OOM, I have a 3060 with 12GB, 37 is already very extreme. 
11. `sudo docker compose up` check if it can run normally, if there are no problems, use `sudo docker compose up -d` to enter background operation.

Other notes: 
- GPU usage seems to be around 30% or so. CPU is running at 100% during operation. 
- The speed has indeed been significantly improved, but it has not yet reached the immediate response level. 
- As the chat history increases, it is more likely to crash, and I have not found the cause of the crash yet, only seen exit code 0. 
- The model path seems to be able to use `/models/llama-2-13b-chat.bin` or only `/models/` directory, otherwise the UI program may have issues.

Directory structure as follows.
```
.
├── data
│   └── run.sh
└── docker-compose.yaml

1 directory, 2 files
```

**Use the llama-gpt cuda version for translation**
